export const SET_MASK_FLAG = "SET_MASK_FLAG";

export const SET_NAVSIDE_FLAG = "SET_NAVSIDE_FLAG";

export const SET_HOMETITLE_FLAG = "SET_HOMETITLE_FLAG";

export const SET_BOTTOMTAB_FLAG = "SET_BOTTOMTAB_FLAG";